name = "Modified Cobblemon Essentials"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "827c87375105766952f8cab13554c217abae14a227593acd4b058bb110da054d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[export]
[export.curseforge]
project-id = 963083

[options]
acceptable-game-versions = ["1.21.1"]
