name = "Modified Cobblemon Essentials"
version = "1.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fada0e631d165dd31df734b431cb838788fcf4d3c00522b22fadb45dd6d145d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[export]
[export.curseforge]
project-id = 963083

[options]
acceptable-game-versions = ["1.21.1"]
