name = "Modified Cobblemon Essentials"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf28b8c953c69ce4bad4aa552ecfc700c2aad341f972745db950b553c00a874f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[export]
[export.curseforge]
project-id = 963083

[options]
acceptable-game-versions = ["1.21.1"]
